Add missing `stdlib.h` include
Fixes:
```c++
   a_dist.c(132): error: identifier "size_t" is undefined
                for(size_t i=0; i < *n; i++) {
                    ^
```